sudo: required
language: generic
services: 
    - docker

before_install:
    - docker build -t mydockerid/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true mydockerid/docker-react npm run test 